### ISSUE TITLE
Slack link dead?

### ISSUE THREAD

**Issue by andreyrd** [webarkit/webarkit#3]
Is the Slack still active? Do you have an updated link?

**Comment by ThorstenBux** [comment]
https://join.slack.com/t/webarkit/shared_invite/zt-154zcqgpj-S0Dg0j4DgvvWlORI2PC1NQ

**Comment by ThorstenBux** [comment]
sorry it times out unfortunately

**Comment by andreyrd** [comment]
Thank you!
